# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class WhatsAppSender():
  def __init__(self):
    pass
  
  def send(self, num='5531996055862', msg = ''):

    userdatadir = '/userData2'
    chromeOptions = webdriver.ChromeOptions()
    # chromeOptions.add_experimental_option('excludeSwitches', ['disable-logging'])
    # chromeOptions.add_argument('log-level=3')
    # chromeOptions.add_argument("--headless") 
    # chromeOptions.add_argument('--enable-gpu')

    chromeOptions.add_argument(f"--user-data-dir={userdatadir}")
    self.driver = webdriver.Chrome(options=chromeOptions) 

    self.driver.set_window_size(1221, 817)
    self.vars = {}
    print(msg)

    self.driver.get(f"https://web.whatsapp.com/send/?phone={num}&text={msg}")

    

    erro = True
    while erro:
        try:
            elem = self.driver.find_element_by_xpath('//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div/p')
            elem.send_keys(Keys.RETURN)
            erro = False
            time.sleep(2)
        except:
            erro = True

    print("ok")
    self.driver.close()

app = WhatsAppSender()

app.send('teste')
app.send('teste 2')
app.send('teste 3')
app.send('teste 4')