# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class WhatsAppSender():
  def __init__(self):
    pass
  
  def send(self, num='5531996055862', msg = ''):

    # userdatadir = '/userData2'
    # chromeOptions = webdriver.ChromeOptions()
    # chromeOptions.add_experimental_option('excludeSwitches', ['disable-logging'])
    # chromeOptions.add_argument('log-level=3')
    # chromeOptions.add_argument("--headless") 
    # chromeOptions.add_argument('--enable-gpu')

    # chromeOptions.add_argument(f"--user-data-dir={userdatadir}")
    # self.driver = webdriver.Chrome(options=chromeOptions) 
    self.driver = webdriver.Chrome() 

    self.driver.get("https://web.whatsapp.com/")

    while len(self.driver.find_elements(By.ID,"side")) < 1:
        time.sleep(1)

    link = f"https://web.whatsapp.com/send?phone={num}&text={msg}"
    self.driver.get(link)
    while len(self.driver.find_elements(By.ID, "side")) < 1:
        time.sleep(1)
        
    while len(self.driver.find_elements(By.XPATH, '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div/p/span')) < 1:
        time.sleep(1)
    self.driver.find_element(By.XPATH, '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div/p/span').send_keys(Keys.ENTER)
    time.sleep(10)


app = WhatsAppSender()

app.send('teste')
